/*
Copyright Mehedi Hasan.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/heheh13/crd/custom/apis/destroyments.heheh.com/v1"
	scheme "github.com/heheh13/crd/custom/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DestroymentsGetter has a method to return a DestroymentInterface.
// A group's client should implement this interface.
type DestroymentsGetter interface {
	Destroyments(namespace string) DestroymentInterface
}

// DestroymentInterface has methods to work with Destroyment resources.
type DestroymentInterface interface {
	Create(ctx context.Context, destroyment *v1.Destroyment, opts metav1.CreateOptions) (*v1.Destroyment, error)
	Update(ctx context.Context, destroyment *v1.Destroyment, opts metav1.UpdateOptions) (*v1.Destroyment, error)
	UpdateStatus(ctx context.Context, destroyment *v1.Destroyment, opts metav1.UpdateOptions) (*v1.Destroyment, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Destroyment, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DestroymentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Destroyment, err error)
	DestroymentExpansion
}

// destroyments implements DestroymentInterface
type destroyments struct {
	client rest.Interface
	ns     string
}

// newDestroyments returns a Destroyments
func newDestroyments(c *DestroymentsV1Client, namespace string) *destroyments {
	return &destroyments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the destroyment, and returns the corresponding destroyment object, and an error if there is any.
func (c *destroyments) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Destroyment, err error) {
	result = &v1.Destroyment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("destroyments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Destroyments that match those selectors.
func (c *destroyments) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DestroymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DestroymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("destroyments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested destroyments.
func (c *destroyments) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("destroyments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a destroyment and creates it.  Returns the server's representation of the destroyment, and an error, if there is any.
func (c *destroyments) Create(ctx context.Context, destroyment *v1.Destroyment, opts metav1.CreateOptions) (result *v1.Destroyment, err error) {
	result = &v1.Destroyment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("destroyments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(destroyment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a destroyment and updates it. Returns the server's representation of the destroyment, and an error, if there is any.
func (c *destroyments) Update(ctx context.Context, destroyment *v1.Destroyment, opts metav1.UpdateOptions) (result *v1.Destroyment, err error) {
	result = &v1.Destroyment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("destroyments").
		Name(destroyment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(destroyment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *destroyments) UpdateStatus(ctx context.Context, destroyment *v1.Destroyment, opts metav1.UpdateOptions) (result *v1.Destroyment, err error) {
	result = &v1.Destroyment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("destroyments").
		Name(destroyment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(destroyment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the destroyment and deletes it. Returns an error if one occurs.
func (c *destroyments) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("destroyments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *destroyments) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("destroyments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched destroyment.
func (c *destroyments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Destroyment, err error) {
	result = &v1.Destroyment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("destroyments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
