/*
Copyright Mehedi Hasan.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	hehehcomv1 "github.com/heheh13/crd-controller/custom/apis/heheh.com/v1"
	versioned "github.com/heheh13/crd-controller/custom/client/clientset/versioned"
	internalinterfaces "github.com/heheh13/crd-controller/custom/client/informers/externalversions/internalinterfaces"
	v1 "github.com/heheh13/crd-controller/custom/client/listers/heheh.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DestroymentInformer provides access to a shared informer and lister for
// Destroyments.
type DestroymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DestroymentLister
}

type destroymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDestroymentInformer constructs a new informer for Destroyment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDestroymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDestroymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDestroymentInformer constructs a new informer for Destroyment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDestroymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HehehV1().Destroyments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HehehV1().Destroyments(namespace).Watch(context.TODO(), options)
			},
		},
		&hehehcomv1.Destroyment{},
		resyncPeriod,
		indexers,
	)
}

func (f *destroymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDestroymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *destroymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hehehcomv1.Destroyment{}, f.defaultInformer)
}

func (f *destroymentInformer) Lister() v1.DestroymentLister {
	return v1.NewDestroymentLister(f.Informer().GetIndexer())
}
